/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    './src/**/*.html', './src/**/*.js',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      primary: 'var(--color-primary)',
      'primary-70': '#00d6c7b3',
      black: colors.black,
      'black-1': 'var(--color-black-1)',
      'black-2': 'var(--color-black-2)',
      'black-3': 'var(--color-black-3)',
      'black-3-90%': '#28282de6',
      white: colors.white,
      'white-1': 'var(--color-white-1)',
      gray: colors.trueGray,
      'gray-1': 'var(--color-gray-1)',
      'gray-2': 'var(--color-gray-2)',
      'gray-3': 'var(--color-gray-3)',
      indigo: colors.indigo,
      red: colors.red,
      rose: colors.rose,
      yellow: colors.amber,
      'yellow-1': 'var(--color-yellow-1)',
      'yellow-2': 'var(--color-yellow-2)',
      green: colors.green,
      blue: colors.blue,
      teal: colors.teal,
      'dark': 'var(--color-dark)',
      'dark-1': 'var(--color-dark-1)',
      'dark-2': 'var(--color-dark-2)',
      'green-1': 'var(--color-green-1)',
      'green-2': 'var(--color-green-2)',
      'green-3': 'var(--color-green-3)',
      'green-4': 'var(--color-green-4)',
      'green-5': 'var(--color-green-5)',
      'blue-1': 'var(--color-blue-1)',
      'orange-1': 'var(--color-orange-1)',
    },
    fontSize: {
      '2xs': '8px',
      xs: '10px',
      sm: '12px',
      'sm-md': '14px',
      md: '16px',
      base: '18px',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '6rem',
      '9xl': '8rem',
    },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1400px',
      '3xl': '1600px',
    },
    extend: {
      zIndex: {
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
      },
      spacing: {
        '1px': '1px',
        2.5: '0.625rem',
        25: '6.25rem',
        88: '22rem',
        100: '25rem',
        106: '26.5rem',
        120: '30rem',
        142: '35.5rem',
        'full-1': 'calc(100% - 2px)',
        '2-full': '200%',
        '160%': '160%',
        '2-screen': '200vw',
        'screen-show-scroll': 'calc(100% - 10px)',
      },
      dropShadow: {
        card: '0px 10px 10px rgba(0, 0, 0, 0.25)',
      },
      boxShadow: {
        'around-3': '0px 0px 3px rgba(0, 0, 0, 0.1)',
        'around-10': '0px 0px 10px rgba(0, 0, 0, 0.1)',
        'around-20': '0px 5px 20px rgba(0, 0, 0, 0.2)',
      },
      lineHeight: {
        'extra-tight': '1.1',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '6xl': '3rem',
        '1/2': '50%',
      },
      maxWidth: {
        56: '14rem',
        66: '16.5rem',
        72: '18rem',
        '3xs': '14rem',
        '2xs': '16rem',
        'screen-xl': '1170px',
        'screen-2xl': '1280px',
      },
      minWidth: {
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        18: '4.5rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        '3xs': '14rem',
        '4xs': '7rem',
        'screen-lg': '1028px',
        'screen-xl': '1280px',
        'screen-2xl': '1440px',
      },
      minHeight: {
        '4xs': '7rem',
        '3xs': '14rem',
      },
      maxHeight: {
        '3xs': '14rem',
        '2xs': '16rem',
        xs: '20rem',
        'screen-2/4': '50vh',
        'screen-3/4': '75vh',
        'screen-n16': 'calc(100vh - (16 * 0.25rem))',
        'screen-n20': 'calc(100vh - (20 * 0.25rem))',
        'screen-2': '200vh',
      },
      transitionProperty: {
        height: 'height',
      },
      rotate: {
        135: '135deg',
      },
      animation: {
        'fade-out': 'fade-out .2s linear forwards',
        'fade-in': 'fade-in .5s ease-out forwards',
        'fade-in-delay': 'fade-in .5s .5s ease-out forwards',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      flex: {
        2: '2 1 0%',
        3: '3 1 0%',
        4: '4 1 0%',
        5: '5 1 0%',
        6: '6 1 0%',
      },
      listStyleType: {
        'lower-alpha': 'lower-alpha',
        square: 'square',
      },
    },
  },
  plugins: [],
  corePlugins: {
    fontFamily: false,
  },
}